### ISSUE TITLE
[1.4.4] Skip brushes are created on decompile instead of clip brushes

### ISSUE THREAD

**Issue by rtandbk** [ata4/bspsrc#179]
When decompiling Half-Life 2: Deathmatch maps, any tools/toolsplayerclip brush is instead replaced with tools/toolsskip.

Steps to reproduce:
1. Add dm_powerhouse to list
2. Other > BSP format > HL2:DM and VMF format > Source 2004 - 2009
3. Load Hammer 
![image](https://github.com/ata4/bspsrc/assets/19803636/c023bcac-c3ed-4ac2-aea8-bd665d25fe29)
![image](https://github.com/ata4/bspsrc/assets/19803636/d39f541a-a79e-42c7-9749-b8e0428aa158)

**Comment by SirYodaJedi** [comment]
This also occurred to me with the regular clip brushes when decompiling Half-Life Deathmatch Source's version of Crossfire; they got converted to skip.

**Comment by rtandbk** [comment]
This issue is still present in v1.4.5 using the same steps to reproduce. I tested the same map using vmex and it created the clips as intended.

**Comment by rihi** [comment]
Fixed with 09f0da9. Will be included in the next release.

**Comment by Pinsplash** [comment]
still having this on the newest version with HL2 maps both with and without using "fix tool textures"

**Comment by rihi** [comment]
The fix will be included in 1.4.6, which is not yet released.
